WITH A AS(
    SELECT
        a.AUTHOR_ID,
        b.CATEGORY,
        SUM(bs.SALES * b.PRICE) AS TOTAL_SALES
    FROM BOOK b
    INNER JOIN BOOK_SALES bs
    ON b.BOOK_ID = bs.BOOK_ID AND '2022-01-01' <= bs.SALES_DATE AND bs.SALES_DATE < '2022-02-01'
    INNER JOIN AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID
    GROUP BY a.AUTHOR_ID, b.CATEGORY
)
SELECT 
    a.AUTHOR_ID,
    au.AUTHOR_NAME,
    a.CATEGORY,
    a.TOTAL_SALES
FROM A a INNER JOIN AUTHOR au ON a.AUTHOR_ID = au.AUTHOR_ID
ORDER BY 1 ASC, 3 DESC;