WITH ID_CATEGORY_TOTAL AS (
SELECT a.AUTHOR_ID, b.CATEGORY, SUM(b.PRICE * bs.SALES)  AS TOTAL_SALES
FROM BOOK_SALES bs
INNER JOIN BOOK b 
ON bs.BOOK_ID = b.BOOK_ID AND SALES_DATE < '2022-02-01' AND SALES_DATE >= '2022-01-01'
INNER JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
GROUP BY a.AUTHOR_ID, b.CATEGORY
)
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, i.CATEGORY, i.TOTAL_SALES
FROM AUTHOR a
INNER JOIN ID_CATEGORY_TOTAL i ON a.AUTHOR_ID = i.AUTHOR_ID
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
