WITH A AS(
    SELECT 
        DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
), B AS (
    SELECT 
        DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)
SELECT 
    a.CART_ID
FROM A a
INNER JOIN B b
ON a.CART_ID = b.CART_ID
ORDER BY a.CART_ID ASC;