WITH RECURSIVE A AS(
    # root
    SELECT
        ID,
        1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        e.ID,
        a.DEPTH + 1 AS DEPTH
    FROM ECOLI_DATA e
    INNER JOIN A a
    ON e.PARENT_ID = a.ID
)
SELECT ID FROM A 
WHERE DEPTH = 3
ORDER BY ID ASC ;