WITH LEAF AS (
    SELECT 
        it1.ITEM_ID  
    FROM ITEM_TREE it1
    LEFT JOIN ITEM_TREE it2
    ON it1.ITEM_ID = it2.PARENT_ITEM_ID
    WHERE it2.ITEM_ID IS NULL
)
SELECT 
    ITEM_ID,
    ITEM_NAME,
    RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN (SELECT * FROM LEAF)
ORDER BY ITEM_ID DESC;