# parent로쓰이지 않은 ID 구하기
# A: parent로 쓰인 ID 구하기
WITH A AS(
    SELECT 
        i1.ITEM_ID
    FROM ITEM_TREE i1
    INNER JOIN ITEM_TREE i2
    ON i1.ITEM_ID = i2.PARENT_ITEM_ID
), 
# B: A에서 없는 ID 구하기
B AS (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE ITEM_ID NOT IN (SELECT ITEM_ID FROM A)
)
SELECT 
    ii.ITEM_ID,
    ii.ITEM_NAME,
    ii.RARITY
FROM B b
INNER JOIN ITEM_INFO ii
ON b.ITEM_ID = ii.ITEM_ID
ORDER BY b.ITEM_ID DESC;