WITH RESALE AS (
    SELECT 
        USER_ID, 
        PRODUCT_ID, 
        COUNT(*) AS TOTAL
    FROM ONLINE_SALE 
    GROUP BY USER_ID, PRODUCT_ID 
)

SELECT 
    USER_ID, 
    PRODUCT_ID 
FROM RESALE 
WHERE TOTAL >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC;