
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS DATE_FORMAT,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE '2022-03-01' <= SALES_DATE AND SALES_DATE < '2022-04-01'

UNION ALL

SELECT 
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS DATE_FORMAT,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM OFFLINE_SALE
WHERE '2022-03-01' <= SALES_DATE AND SALES_DATE < '2022-04-01'

ORDER BY DATE_FORMAT ASC, PRODUCT_ID ASC, USER_ID ASC;
