WITH PROBLEM1 AS(
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE IN('세단', 'SUV')
), PROBLEM2_1 AS(
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
), PROBLEM2 AS(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_ID NOT IN (SELECT CAR_ID FROM PROBLEM2_1)
)


SELECT 
    p1.CAR_ID,
    p1.CAR_TYPE,
    ROUND(p1.DAILY_FEE * 30 * ((100 - ccdp.DISCOUNT_RATE) / 100)) AS FEE
FROM PROBLEM1 p1
INNER JOIN PROBLEM2 p2
ON p1.CAR_ID = p2.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  ccdp
ON p1.CAR_TYPE = ccdp.CAR_TYPE AND ccdp.DURATION_TYPE = '30일 이상'   
HAVING 500000<= FEE AND FEE < 2000000
ORDER BY FEE DESC, p1.CAR_TYPE ASC, p1.CAR_ID DESC;