

# 세단과 SUV, 30일간 금액이 500000이상 200만원미만

# ID, 종류ㅡ 대여금액
WITH A AS (
    SELECT 
        CAR_ID,
        CAR_TYPE,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN('세단', 'SUV')
), B AS(
    SELECT
        a.CAR_ID,
        a.CAR_TYPE,
        a.DAILY_FEE * 30 * (100 - (REPLACE(c.DISCOUNT_RATE, '%', ''))) / 100 AS FEE
    FROM A a
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
    ON a.CAR_TYPE = c.CAR_TYPE AND c.DURATION_TYPE = '30일 이상'
), C AS(
    # 11월 동안 대여 가능은 start <= 11-30 AND end >= 11-01
    SELECT 
        CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
SELECT 
    CAR_ID, 
    CAR_TYPE, 
    ROUND(FEE) AS FEE
FROM B 
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM C) AND 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;