WITH A AS(
    SELECT
    RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK,
    REST_ID
    FROM REST_INFO
)
SELECT 
    r.FOOD_TYPE,
    r.REST_ID,
    r.REST_NAME,
    r.FAVORITES
FROM REST_INFO r
INNER JOIN A a
ON r.REST_ID = a.REST_ID AND a.RNK = 1
ORDER BY r.FOOD_TYPE DESC;
