WITH RANK_REST AS (
    SELECT    
        REST_ID,
        RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rnk
    FROM REST_INFO
)

SELECT ri.FOOD_TYPE, ri.REST_ID,ri.REST_NAME, ri.FAVORITES 
FROM REST_INFO ri 
INNER JOIN RANK_REST rr
ON ri.REST_ID = rr.REST_ID AND rr.rnk = 1
ORDER BY FOOD_TYPE DESC;
