WITH A AS (
    SELECT
        ID,
        PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY) AS RNK
    FROM ECOLI_DATA
)

SELECT
    e.ID,
    CASE
        WHEN 0.25 >= RNK THEN 'LOW'
        WHEN 0.5 >= RNK THEN 'MEDIUM'
        WHEN 0.75 >= RNK THEN 'HIGH'
        ELSE 'CRITICAL' 
    END AS COLONY_NAME
FROM ECOLI_DATA e
INNER JOIN A a
ON e.ID = a.ID
ORDER BY e.ID ASC;