WITH USER_IDS AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(1) >= 3
)
SELECT 
    USER_ID,
    NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, 
    INSERT(INSERT(TLNO, 4, 0, '-'),9, 0, '-' ) AS 전화번호
FROM USED_GOODS_USER
WHERE USER_ID IN (SELECT WRITER_ID FROM USER_IDS)
ORDER BY USER_ID DESC;