WITH A AS(
    SELECT 
        WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)  
SELECT 
    ugu.USER_ID,
    ugu.NICKNAME,
    CONCAT(ugu.CITY, ' ', ugu.STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
    CONCAT(LEFT(ugu.TLNO, 3), '-', SUBSTRING(ugu.TLNO,4,4), '-', RIGHT(ugu.TLNO, 4)  ) AS 전화번호
    
FROM USED_GOODS_USER ugu
INNER JOIN A a
ON ugu.USER_ID = a.WRITER_ID
ORDER BY ugu.USER_ID DESC;