WITH A AS(
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE NOT SEX_UPON_INTAKE LIKE 'Spayed%' AND NOT SEX_UPON_INTAKE LIKE 'Neutered%'
)
SELECT 
    ao.ANIMAL_ID,
    ao.ANIMAL_TYPE,
    ao.NAME
FROM ANIMAL_OUTS ao
INNER JOIN A a
ON a.ANIMAL_ID = ao.ANIMAL_ID AND (ao.SEX_UPON_OUTCOME LIKE 'Spayed%' OR ao.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ao.ANIMAL_ID;