WITH REST AS (
    SELECT 
        i.REST_ID,
        i.REST_NAME, 
        i.FOOD_TYPE, 
        i.FAVORITES,   
        i.ADDRESS, 
        r.REVIEW_SCORE
    FROM REST_INFO i
    INNER JOIN REST_REVIEW r 
    ON i.REST_ID = r.REST_ID
)

SELECT 
    REST_ID, 
    REST_NAME, 
    FOOD_TYPE, 
    FAVORITES, 
    ADDRESS, 
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST 
WHERE SUBSTRING(ADDRESS, 1, 2) = '서울'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;