SELECT 
    YEAR(os.SALES_DATE) AS YEAR, 
    MONTH(os.SALES_DATE) AS MONTH, 
    ui.GENDER AS GENDER,
    COUNT(DISTINCT ui.USER_ID) AS USERS
FROM ONLINE_SALE os
INNER JOIN USER_INFO ui
ON os.USER_ID = ui.USER_ID AND ui.GENDER IS NOT NULL
GROUP BY YEAR,MONTH,GENDER
ORDER BY 1, 2, 3;
