# 년 월 성별 별로 상품을 구매한 회원수 집계
# 년 월 성별로 group 후 회원 COUNT하기
# 1. JOIN
WITH A AS(
    SELECT
        YEAR(o.SALES_DATE) AS YEAR,
        MONTH(o.SALES_DATE) AS MONTH,
        u.USER_ID,
        u.GENDER
    FROM ONLINE_SALE o
    INNER JOIN USER_INFO u
    ON o.USER_ID = u.USER_ID AND u.GENDER IS NOT NULL
)
SELECT 
    YEAR, 
    MONTH, 
    GENDER, 
    COUNT(DISTINCT USER_ID) AS SALES_AMOUNT
FROM A
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3;