-- 2021년 가입한 사람
WITH USER_2021 AS (
    SELECT 
        USER_ID,
        COUNT(USER_ID) OVER() AS TOTAL
    FROM USER_INFO
    WHERE '2021-01-01' <= JOINED AND JOINED < '2022-01-01'
)

SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT os.USER_ID) / TOTAL, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE os
INNER JOIN USER_2021 u2
ON os.USER_ID = u2.USER_ID
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE)
ORDER BY 1, 2