# 2021년 가입 회원 PERCENT_RANK?? PERCENT??
# 년 월 별로 그룹해 회원수 및 비율 출력
WITH A AS(
    SELECT
        USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
), B AS (
    SELECT
        o.USER_ID,
        YEAR(o.SALES_DATE) AS YEAR,
        MONTH(o.SALES_DATE) AS MONTH
    FROM ONLINE_SALE o    
    INNER JOIN A a
    ON o.USER_ID = a.USER_ID
), C AS(
    SELECT COUNT(DISTINCT USER_ID) AS TOTAL FROM A
)
SELECT 
    YEAR,
    MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT USER_ID) / TOTAL, 1) AS PURCHASED_RATIO
FROM B
CROSS JOIN C
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;

