WITH RECURSIVE TREE AS(
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT 
        e.ID, 
        e.PARENT_ID, 
        t.GENERATION + 1
    FROM ECOLI_DATA e 
    INNER JOIN TREE t ON e.PARENT_ID = t.ID
)

SELECT
COUNT(*) AS COUNT,
GENERATION
FROM TREE t 
WHERE NOT EXISTS(
    SELECT 1 
    FROM ECOLI_DATA e 
    WHERE e.PARENT_ID = t.ID
) 
GROUP BY GENERATION ORDER BY GENERATION;