# 자식이 없다 내 ID를 parent로 쓰는게 없다.
WITH RECURSIVE A AS(
    SELECT
        ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        e.ID,
        a.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e
    INNER JOIN A a
    ON e.PARENT_ID = a.ID
), B AS(
    SELECT
        ID
    FROM ECOLI_DATA
    WHERE ID NOT IN (SELECT IFNULL(PARENT_ID, 0) FROM ECOLI_DATA)
)
SELECT 
    COUNT(1) AS COUNT, 
    GENERATION
FROM A a 
INNER JOIN B b 
ON a.ID = b.ID
GROUP BY GENERATION
ORDER BY GENERATION ASC;