WITH CAR AS (
    SELECT
        CAR_ID,
        CASE
            WHEN START_DATE <= DATE('2022-10-16') AND DATE('2022-10-16') <= END_DATE THEN 1
            ELSE 0
        END AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
), CAR_GROUP AS (
    SELECT 
        CAR_ID,
        SUM(AVAILABILITY) AS AVAILABILITY_COUNT
    FROM CAR 
    GROUP BY CAR_ID
)
SELECT 
    CAR_ID,
    CASE 
        WHEN AVAILABILITY_COUNT = 1 THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_GROUP
ORDER BY CAR_ID DESC;