WITH QUARTER_TABLE AS(
    SELECT 
        CASE
            WHEN 1 <= MONTH(DIFFERENTIATION_DATE) 
            AND MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
            WHEN 4 <= MONTH(DIFFERENTIATION_DATE) 
            AND MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
            WHEN 7 <= MONTH(DIFFERENTIATION_DATE) 
            AND MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
            ELSE '4Q'
        END
        AS QUARTER
    FROM ECOLI_DATA 
)
SELECT 
    QUARTER, 
    COUNT(1) AS ECOLI_COUNT 
FROM QUARTER_TABLE
GROUP BY QUARTER
ORDER BY QUARTER ASC;