WITH PROBLEM1_1 AS(
    SELECT
        ai.ANIMAL_ID AS IN_ID,
        ao.ANIMAL_ID AS OUT_ID
    FROM ANIMAL_INS ai
    LEFT JOIN ANIMAL_OUTS ao
    ON ai.ANIMAL_ID = ao.ANIMAL_ID
), PROBLEM1 AS(
    SELECT 
        IN_ID AS ANIMAL_ID
    FROM PROBLEM1_1
    WHERE OUT_ID IS NULL
)
SELECT 
    NAME,
    DATETIME
FROM ANIMAL_INS 
WHERE ANIMAL_ID IN (SELECT ANIMAL_ID FROM PROBLEM1)
ORDER BY DATETIME ASC
LIMIT 3

