WITH PROBLEM1 AS(
    SELECT 
        * 
    FROM FOOD_ORDER 
    WHERE '2022-05-01' <= PRODUCE_DATE AND PRODUCE_DATE < '2022-06-01'
), PROBLEM2 AS(
    SELECT 
        fp.PRODUCT_ID,
        fp.PRODUCT_NAME,
        SUM(fp.PRICE * p1.AMOUNT) AS TOTAL_SALES
    FROM FOOD_PRODUCT fp
    INNER JOIN PROBLEM1 p1
    ON fp.PRODUCT_ID = p1.PRODUCT_ID
    GROUP BY fp.PRODUCT_ID
)
SELECT * FROM PROBLEM2 ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;