WITH A AS(
    SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS TOTAL
    FROM FOOD_ORDER
    WHERE '2022-05-01' <= PRODUCE_DATE AND PRODUCE_DATE < '2022-06-01'
    GROUP BY PRODUCT_ID
)
SELECT 
    fp.PRODUCT_ID,
    fp.PRODUCT_NAME,
    a.TOTAL * fp.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT fp
INNER JOIN A a
ON fp.PRODUCT_ID = a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID ASC;

