WITH TRUCK AS (
    SELECT 
        crcrh.HISTORY_ID, 
        TIMESTAMPDIFF(DAY, crcrh.START_DATE,crcrh.END_DATE) + 1 AS DAYS, 
        crcc.DAILY_FEE * (TIMESTAMPDIFF(DAY, crcrh.START_DATE,crcrh.END_DATE) + 1) AS FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
    INNER JOIN CAR_RENTAL_COMPANY_CAR  crcc
    ON crcrh.CAR_ID = crcc.CAR_ID AND crcc.CAR_TYPE = '트럭'
), TRUCK_DISCOUNT AS (
    SELECT 
        LEFT(DURATION_TYPE, LENGTH(DURATION_TYPE - 4)) AS DURATION,
        (1 - DISCOUNT_RATE * 0.01) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭'
)
# SELECT * FROM TRUCK_DISCOUNT
SELECT 
    t.HISTORY_ID,
    CASE 
        WHEN td.DURATION IS NULL THEN t.FEE 
        ELSE ROUND(t.FEE * td.DISCOUNT_RATE) 
    END AS FEE
    
FROM TRUCK t
LEFT JOIN TRUCK_DISCOUNT td
ON 
(7 <= t.DAYS AND t.DAYS <  30 AND td.DURATION = 7) 
OR (30 <= t.DAYS AND t.DAYS < 90 AND td.DURATION = 30)
OR (90 <= t.DAYS AND td.DURATION = 90)
ORDER BY FEE DESC, HISTORY_ID DESC;