# 트럭인 자동차에 대한 금액 구하기
# 대여기록 ID, 금액 리스트 출력
# 1. 트럭인 CAR_ID와 DAILY_FEE추출
# 2. 기간 별로 할인률 계산 
# 3. 금액계산
WITH A AS (
    SELECT 
        CAR_ID,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
), B AS(
    SELECT
        crch.HISTORY_ID,
        a.DAILY_FEE * (TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1) TOTAL_FEE,
        TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crch
    INNER JOIN A a
    ON crch.CAR_ID = a.CAR_ID
), C AS(
    SELECT 
        SUBSTRING(DURATION_TYPE, 1, CHAR_LENGTH(DURATION_TYPE - 3)) AS DURATION,
        (100 - SUBSTRING(DISCOUNT_RATE, 1, CHAR_LENGTH(DISCOUNT_RATE - 1))) / 100 AS DISCOUNT
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)
SELECT 
    HISTORY_ID,
    CASE
        WHEN 90 <= DURATION THEN (SELECT DISCOUNT FROM C WHERE DURATION = 90) * TOTAL_FEE
        WHEN 30 <= DURATION THEN (SELECT DISCOUNT FROM C WHERE DURATION = 30) * TOTAL_FEE
        WHEN 7 <= DURATION THEN (SELECT DISCOUNT FROM C WHERE DURATION = 7) * TOTAL_FEE
        ELSE TOTAL_FEE
    END AS FEE
FROM B b
ORDER BY FEE DESC, HISTORY_ID DESC;