WITH A AS(
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
), B AS(
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)
SELECT
    a.FLAVOR
FROM A a
INNER JOIN B b
ON a.FLAVOR = b.FLAVOR
ORDER BY a.TOTAL_ORDER + b.TOTAL_ORDER DESC
LIMIT 3;
