WITH JULY_FLAVOR AS (
    SELECT 
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)


SELECT
    fh.FLAVOR
FROM FIRST_HALF fh 
INNER JOIN JULY_FLAVOR j
ON fh.FLAVOR = j.FLAVOR
ORDER BY fh.TOTAL_ORDER + j.TOTAL_ORDER DESC
LIMIT 3;