WITH FILTER_APPOINTMET AS(
    SELECT *
    FROM APPOINTMENT
    WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
          AND APNT_CNCL_YN = 'N'
          AND MCDP_CD = 'CS'
)
SELECT 
    fa.APNT_NO,
    p.PT_NAME,
    p.PT_NO,
    fa.MCDP_CD,
    d.DR_NAME,
    fa.APNT_YMD
FROM FILTER_APPOINTMET fa
INNER JOIN PATIENT p
ON fa.PT_NO = p.PT_NO
INNER JOIN DOCTOR d
ON fa.MDDR_ID = d.DR_ID
ORDER BY fa.APNT_YMD;