WITH A AS (
    SELECT
        APNT_YMD,
        APNT_NO,
        PT_NO,
        MDDR_ID
    FROM APPOINTMENT 
    WHERE '2022-04-13' <= APNT_YMD AND APNT_YMD < '2022-04-14' AND NOT APNT_CNCL_YN = 'Y'
)
SELECT 
    a.APNT_NO,
    p.PT_NAME,
    p.PT_NO,
    d.MCDP_CD,
    d.DR_NAME,
    a.APNT_YMD
FROM A a 
INNER JOIN DOCTOR d 
ON a.MDDR_ID = d.DR_ID
INNER JOIN PATIENT p
ON a.PT_NO = p.PT_NO 
ORDER BY a.APNT_YMD;