# 0 ~23시까지 입양 확인
WITH RECURSIVE TIME AS(
    SELECT 0 AS DEPTH
    
    UNION ALL

    SELECT DEPTH + 1
    FROM TIME
    WHERE DEPTH < 23
), B AS(
    SELECT 
        HOUR(DATETIME) AS HOUR,
        COUNT(1) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)
SELECT
    DEPTH AS HOUR,
    IFNULL(b.COUNT, 0) AS COUNT
FROM TIME t
LEFT JOIN B b
ON t.DEPTH = b.HOUR
ORDER BY 1 ASC;