WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 FROM HOUR_TABLE
    WHERE HOUR < 23
), ANIMAL_HOUR AS (
    SELECT 
        HOUR(DATETIME) AS HOUR,
        COUNT(1) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)


SELECT 
    HOUR_TABLE.HOUR,
    IFNULL(ANIMAL_HOUR.COUNT, 0) AS COUNT
FROM HOUR_TABLE
LEFT JOIN ANIMAL_HOUR
ON HOUR_TABLE.HOUR = ANIMAL_HOUR.HOUR