WITH A AS (
    SELECT 
        SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    GROUP BY CATEGORY
)
SELECT 
    d.ID,
    d.EMAIL,
    d.FIRST_NAME,
    d.LAST_NAME
FROM DEVELOPERS d
INNER JOIN A a
ON a.CODE & d.SKILL_CODE != 0
ORDER BY d.ID ASC;