WITH FRONTEND AS(
    SELECT 
        SUM(CODE) AS FRONTCODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT 
    d.ID,
    d.EMAIL,
    d.FIRST_NAME,
    d.LAST_NAME
FROM DEVELOPERS d
INNER JOIN FRONTEND f
ON d.SKILL_CODE & f.FRONTCODE > 0
ORDER BY d.ID ASC;
