WITH PROBLEM1 AS(
    SELECT * 
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
), PROBLEM2 AS (
    SELECT 
        WRITER_ID,
        SUM(PRICE) AS TOTAL
    FROM PROBLEM1
    GROUP BY WRITER_ID
    HAVING TOTAL >= 700000
)
SELECT 
    ugu.USER_ID,
    ugu.NICKNAME,
    p2.TOTAL AS TOTAL_SALES
FROM USED_GOODS_USER ugu
INNER JOIN PROBLEM2 p2
ON ugu.USER_ID = p2.WRITER_ID
ORDER BY 3 ASC;