WITH A AS(
    SELECT 
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)
SELECT 
    ugu.USER_ID,
    ugu.NICKNAME,
    a.TOTAL_SALES
FROM USED_GOODS_USER ugu
INNER JOIN A a
ON ugu.USER_ID = a.WRITER_ID
ORDER BY TOTAL_SALES ASC;