-- 리뷰 많은 사람 ID 찾기
WITH PROBLEM1 AS (
    SELECT
        MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(1) DESC
    LIMIT 1
)
SELECT 
    mp.MEMBER_NAME,
    rr.REVIEW_TEXT,
    DATE_FORMAT(rr.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW rr
INNER JOIN MEMBER_PROFILE mp
ON rr.MEMBER_ID = mp.MEMBER_ID AND rr.MEMBER_ID IN(SELECT MEMBER_ID FROM PROBLEM1) 
ORDER BY 3 ASC, 2 ASC;
