# 리뷰를 가장 많이 작성한 회원의 리뷰
WITH A AS(
    SELECT 
        MEMBER_ID,
        COUNT(1) AS TOTAL
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY TOTAL DESC
    LIMIT 1
), B AS (
    SELECT 
        MEMBER_ID,
        REVIEW_TEXT,
        REVIEW_DATE
    FROM REST_REVIEW 
    WHERE MEMBER_ID IN(SELECT MEMBER_ID FROM A)
)
SELECT 
    m.MEMBER_NAME,
    b.REVIEW_TEXT,
    DATE_FORMAT(b.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE m
INNER JOIN B b
ON m.MEMBER_ID = b.MEMBER_ID
ORDER BY 3 ASC, 2 ASC;