WITH RARE AS (
    SELECT info.ITEM_ID FROM ITEM_INFO info 
    WHERE info.RARITY = 'RARE'
), RARE_UPGRADE AS (
    SELECT it.ITEM_ID FROM ITEM_TREE it
    INNER JOIN 
    RARE r ON r.ITEM_ID = it.PARENT_ITEM_ID
    GROUP BY it.ITEM_ID
)
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i 
INNER JOIN RARE_UPGRADE ru ON i.ITEM_ID = ru.ITEM_ID
ORDER BY i.ITEM_ID DESC;

