WITH CAR_DATE AS(
    SELECT
    *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-08-01' <= START_DATE AND START_DATE < '2022-11-01'
), CAR_COUNT AS(
    SELECT
        CAR_ID,
        COUNT(1) AS RECORDS
    FROM CAR_DATE
    GROUP BY CAR_ID
    HAVING RECORDS >= 5
), CAR_MONTHLY AS (
    SELECT 
        cd.CAR_ID, 
        cd.START_DATE 
    FROM CAR_DATE cd 
    INNER JOIN CAR_COUNT cc
    ON cd.CAR_ID = cc.CAR_ID
)

SELECT  
    DATE_FORMAT(START_DATE, '%m') AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_MONTHLY 
GROUP BY CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m')
HAVING COUNT(*) > 0
ORDER BY 1, 2 DESC;