WITH A AS(
    SELECT 
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-08-01' <= START_DATE AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(1) >= 5
), B AS(
    SELECT 
        c1.CAR_ID AS CAR_ID,
        MONTH(c1.START_DATE) AS MONTH,
        COUNT(1) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c1 
    INNER JOIN A a
    ON c1.CAR_ID = a.CAR_ID
    GROUP BY c1.CAR_ID, MONTH(c1.START_DATE)
    
)
SELECT 
    MONTH,
    CAR_ID,
    RECORDS
FROM B
WHERE MONTH IN('8', '9', '10')
ORDER BY 1 ASC, 2 DESC;