WITH MAX_DATA AS(
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY 
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    (m.MAX_SIZE_OF_COLONY - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e 
INNER JOIN MAX_DATA m 
ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;