WITH ICECREAM AS (
    SELECT f.SHIPMENT_ID, f.FLAVOR, f.TOTAL_ORDER, i.INGREDIENT_TYPE 
    FROM FIRST_HALF AS f
    INNER JOIN ICECREAM_INFO AS i on f.FLAVOR = i.FLAVOR
) 

SELECT FLAVOR FROM ICECREAM WHERE TOTAL_ORDER >= 3000 AND INGREDIENT_TYPE = 'fruit_based';