WITH A AS(
    SELECT
        DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-10-01' AND START_DATE < '2022-11-01'
), B AS(
    SELECT 
        DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
)
SELECT a.CAR_ID FROM A a INNER JOIN B b ON a.CAR_ID = b.CAR_ID ORDER BY a.CAR_ID DESC;
