SELECT crrh.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crrh
INNER JOIN CAR_RENTAL_COMPANY_CAR crcc
ON crrh.CAR_ID = crcc.CAR_ID AND MONTH(crrh.START_DATE) = 10 AND crcc.CAR_TYPE = '세단'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;