WITH FISH AS (
    SELECT 
        MAX(LENGTH) AS MAX_LENGTH, 
        FISH_TYPE 
    FROM FISH_INFO  
    GROUP BY FISH_TYPE
), FISH_FULL AS (
    SELECT i.ID, n.FISH_NAME, i.LENGTH, i.FISH_TYPE
    FROM FISH_INFO i
    INNER JOIN FISH_NAME_INFO n
    ON i.FISH_TYPE = n.FISH_TYPE
)

SELECT ff.ID, ff.FISH_NAME, ff.LENGTH
FROM FISH_FULL ff
INNER JOIN FISH f
ON f.FISH_TYPE = ff.FISH_TYPE
WHERE f.MAX_LENGTH = ff.LENGTH AND f.FISH_TYPE = ff.FISH_TYPE
ORDER BY ff.ID;


