WITH A AS (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RNK
    FROM FISH_INFO
), B AS(
    SELECT * FROM A WHERE RNK = 1
)
SELECT
    b.ID,
    fn.FISH_NAME,
    b.LENGTH
FROM B b
INNER JOIN FISH_NAME_INFO fn
ON b.FISH_TYPE = fn.FISH_TYPE
ORDER BY b.ID
