SELECT ID, FISH_NAME, LENGTH
FROM(SELECT 
        i.ID,
        n.FISH_NAME,
        i.LENGTH,
        RANK() OVER(PARTITION BY i.FISH_TYPE ORDER BY i.LENGTH DESC) AS rnk
      FROM FISH_INFO i
      INNER JOIN FISH_NAME_INFO n
      ON i.FISH_TYPE = n.FISH_TYPE
    ) AS RANK_FISH    
WHERE rnk = 1
ORDER BY ID ASC;