WITH HIGH_SCORE AS (
    SELECT 
        EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE 
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
    ORDER BY SCORE DESC 
    LIMIT 1
)

SELECT
    hs.SCORE AS SCORE,
    hs.EMP_NO,
    he.EMP_NAME,
    he.POSITION,
    he.EMAIL
FROM HIGH_SCORE hs
INNER JOIN HR_EMPLOYEES he
ON hs.EMP_NO = he.EMP_NO;