WITH A AS (
    SELECT 
        DEPT_ID,
        ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT 
    a.DEPT_ID,
    hd.DEPT_NAME_EN,
    a.AVG_SAL
FROM A a
INNER JOIN HR_DEPARTMENT hd
ON a.DEPT_ID = hd.DEPT_ID
ORDER BY AVG_SAL DESC;
