WITH HR_SAL AS (
    SELECT
        hd.DEPT_ID,
        AVG(SAL) AS AVG_SAL
    FROM HR_DEPARTMENT hd
    INNER JOIN HR_EMPLOYEES he
    ON hd.DEPT_ID = he.DEPT_ID
    GROUP BY hd.DEPT_ID
)
SELECT 
    hd.DEPT_ID,
    hd.DEPT_NAME_EN,
    ROUND(hs.AVG_SAL, 0) AS AVG_SAL
FROM HR_DEPARTMENT hd
INNER JOIN HR_SAL hs
ON hd.DEPT_ID = hs.DEPT_ID
ORDER BY 3 DESC;