WITH TOP AS (
    SELECT
        BOARD_ID,
        RANK() OVER(ORDER BY VIEWS DESC) AS RNK
    FROM USED_GOODS_BOARD
), TOP_ONE AS (
    SELECT BOARD_ID FROM TOP WHERE RNK = 1
)

SELECT 
    CONCAT('/home/grep/src/', ugf.BOARD_ID, '/', ugf.FILE_ID, ugf.FILE_NAME, ugf.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE ugf
INNER JOIN TOP_ONE top
ON ugf.BOARD_ID = top.BOARD_ID
ORDER BY ugf.FILE_ID DESC;
