WITH A AS(
    SELECT
        BOARD_ID,
        RANK() OVER(ORDER BY VIEWS DESC) AS RNK
    FROM USED_GOODS_BOARD 
), B AS (
    SELECT BOARD_ID FROM A WHERE RNK = 1
)
SELECT
    CONCAT('/home/grep/src/', b.BOARD_ID, '/', ug.FILE_ID, ug.FILE_NAME, ug.FILE_EXT)
    AS FILE_PATH
FROM USED_GOODS_FILE ug
INNER JOIN B b
ON ug.BOARD_ID = b.BOARD_ID
ORDER BY ug.FILE_ID DESC;