WITH A AS (
    SELECT 
        BOOK_ID,
        SUM(SALES) TOTAL
    FROM BOOK_SALES
    WHERE '2022-01-01' <= SALES_DATE AND SALES_DATE < '2022-02-01'
    GROUP BY BOOK_ID
), B AS (
    SELECT 
        CATEGORY,
        SUM(a.TOTAL) AS TOTAL_SALES
    FROM BOOK b
    INNER JOIN A a
    ON b.BOOK_ID = a.BOOK_ID
    GROUP BY b.CATEGORY
)
SELECT * FROM B ORDER BY CATEGORY ASC;