WITH BOOK_SUM AS (
    SELECT 
        b.CATEGORY,
        bs.SALES
    FROM BOOK b
    INNER JOIN BOOK_SALES bs
    ON bs.BOOK_ID = b.BOOK_ID AND '2022-01-01' <= bs.SALES_DATE AND bs.SALES_DATE < '2022-02-01'  
)
SELECT 
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM BOOK_SUM
GROUP BY CATEGORY
ORDER BY 1;