WITH A AS(
    SELECT
         PRODUCT_ID,
         RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
)
SELECT 
    f.CATEGORY,
    f.PRICE AS MAX_PRICE,
    f.PRODUCT_NAME
FROM FOOD_PRODUCT f
INNER JOIN A a 
ON f.CATEGORY IN ('과자', '국', '김치', '식용유') AND f.PRODUCT_ID = a.PRODUCT_ID AND a.RNK = 1
ORDER BY f.PRICE DESC;

