WITH A AS(
    SELECT
        FISH_TYPE,
        IFNULL(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
), B AS(
    SELECT
        FISH_TYPE,
        COUNT(1) AS FISH_COUNT,
        MAX(LENGTH) AS MAX_LENGTH,
        AVG(LENGTH)
    FROM A
    GROUP BY FISH_TYPE
    HAVING AVG(LENGTH) >= 33
)
SELECT 
    FISH_COUNT,
    MAX_LENGTH,
    FISH_TYPE
FROM B
ORDER BY FISH_TYPE;