WITH FrontEnd AS(
    SELECT
        SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    GROUP BY CATEGORY
), Python AS (
    SELECT 
        SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
    GROUP BY NAME
), CSHARP AS (
    SELECT
        SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
    GROUP BY NAME
), A AS(
    SELECT 
        CASE
            WHEN SKILL_CODE & (SELECT CODE FROM Frontend) != 0 AND  
                 SKILL_CODE & (SELECT CODE FROM Python) != 0 THEN 'A'
            WHEN SKILL_CODE & (SELECT CODE FROM CSHARP) != 0 THEN 'B'
            WHEN SKILL_CODE & (SELECT CODE FROM Frontend) != 0 THEN 'C'
        END AS GRADE,
        ID,
        EMAIL
    FROM DEVELOPERS

)
SELECT * FROM A WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;
