WITH PRICE_G AS(
    SELECT PRICE DIV 10000 AS PRICE_GROUP 
    FROM PRODUCT
)

SELECT 
    PRICE_GROUP * 10000 AS PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM PRICE_G 
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC;
